[build]
target = "x86_64-rust_os.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
# runner = "qemu-system-x86_64 -drive format=raw,file=target\x86_64-rust_os\debug\bootimage-rust-os.bin"